# Generated by Django 4.1.4 on 2022-12-08 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=500)),
                ('proyecto', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.tags')),
            ],
        ),
    ]
