# Generated by Django 4.1.4 on 2022-12-08 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_remove_proyectos_foto_proyectos_archivo_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='archivo_foto',
        ),
    ]
