# Generated by Django 4.1.4 on 2022-12-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_remove_proyectos_archivo_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('momento_registrado', models.DateField(null=True)),
            ],
        ),
    ]
