# Generated by Django 4.1.4 on 2022-12-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_alter_visitantes_momento_registrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion',
            field=models.CharField(max_length=600),
        ),
    ]
